server:
  address: 0.0.0.0
  port: 8088

spring:
  application:
    name: back-end
  data:
    mongodb:
      uri: mongodb+srv://sonbuithanh306:sonbuidatabase2708@cluster-database-mongod.fs2ls.mongodb.net/?retryWrites=true&w=majority&appName=Cluster-DataBase-MongoDB
      database: database
management:
  endpoints:
    web:
      exposure:
        include: health,info, mappings
  endpoint:
    health:
      show-details: always
